### ISSUE TITLE
Places autocomplete broken in production: importLibrary is not a function

### ISSUE THREAD

**Issue by DoraBuilds** [DoraBuilds/olia-your-daily-operations#784]
Regression from #783. Production console shows:

```
Uncaught TypeError: window.google.maps.importLibrary is not a function
    at Ds.t.onload
```

`PlacesAutocompleteInput.tsx` calls `google.maps.importLibrary("places")` inside the script's `onload` handler. That's unnecessary given the script is already loaded with `&libraries=places` in the URL — the new `AutocompleteSuggestion`/`Place` classes should be read directly off `google.maps.places`, the same way the old `AutocompleteService`/`PlacesService` were, without the extra `importLibrary` round trip.

Fix: drop `importLibrary`, access `google.maps.places.AutocompleteSuggestion` / `google.maps.places.Place` (well, `AutocompleteSessionToken` too) directly after script `onload`, same access pattern as before.
